Makefile: Add format rule
saagarjha/unxip pull request #28
Opened 2023-04-17 22:17 UTC by TheRealKeto

Due to the Makefile consolidating the building, installing, and removal of the project, I thought it'd be best to also include a rule that simply runs `swift-format`.

The changes to the source code of the project were made after running the Makefile rule, which I thought I'd also commit here, as well as document the rule over the command that it runs on the README.

2023-04-18 11:04 UTC, saagarjha requested changes
I like the idea of a format rule in the Makefile. However, you should probably fix these first. (I also made changes to the file recently so you should probably rebase your code.)

2023-04-18 11:04 UTC, saagarjha commented on README.md
> -$ swift-format -i *.swift
I largely consider the makefile to be convenience rather than the advertised ways to do things

2023-04-19 18:47 UTC, TheRealKeto commented
I've resolved wanted changes. Feel free to review again.

2023-04-21 07:12 UTC, saagarjha commented
Happy to merge the Makefile changes as a single commit. Would you like to clean it up or are you OK with me doing that on your behalf?

2023-04-21 22:23 UTC, TheRealKeto commented
Please continue on my behalf.

2023-04-22 10:47 UTC, saagarjha commented
@TheRealKeto since this commit has your name on it please review it before I merge it. (In particular, add a Signed-off-by: and resign it if you'd like.)

2023-04-22 17:28 UTC, TheRealKeto commented
I've resigned the commit and added a signed-off message. Please review.

2023-04-22 23:57 UTC, saagarjha approved these changes

2023-04-22 23:57 UTC, merged

2023-04-22 23:57 UTC, saagarjha commented
Thanks!